Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,6 +5,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@master
+      
       - name: Run Snyk to check for vulnerabilities
         uses: snyk/actions/node@master
         continue-on-error: true # To make sure that SARIF upload gets called
@@ -13,7 +14,23 @@ jobs:
         with:
           command: test
           args: --sarif-file-output=snyk.sarif --all-projects
+          
       - name: Upload result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file: snyk.sarif
+          
+      - name: Check Snyk test result
+        id: snyk_result
+        run: |
+          if [[ "${{ steps.snyk_test.outcome }}" != "success" ]]; then
+            echo "Snyk test failed. Exiting..."
+            exit 1
+          fi
+          echo "Code is secure. Proceeding to archive."
+        
+      - name: Archive code in a ZIP
+        uses: actions/upload-artifact@v3
+        with:
+          name: secure-code-archive
+          path: .
