Update main.yml
Final action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,7 +19,16 @@ jobs:
         uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file: snyk.sarif
-        
+          
+      - name: Check Snyk test result
+        id: snyk_result
+        run: |
+          if [[ "${{ steps.snyk_test.outcome }}" != "success" ]]; then
+            echo "Snyk test failed. Exiting..."
+            exit 1
+          fi
+          echo "Code is secure. Proceeding to archive."
+          
       - name: Archive code in a ZIP
         uses: actions/upload-artifact@v3
         with:
